In [1]:
import torch as t
t.__version__

'1.1.0'

# Tensor

## Bulid tensor

### Using Tensor() 

In [2]:
a = t.Tensor(2,3) # by assign the shape of the tensor
a

tensor([[1.7181e+19, 1.8990e+28, 1.0834e-08],
        [7.0294e+28, 6.1949e-04, 3.9155e-02]])

In [4]:
b = t.Tensor([[1,2,3],[4,5,6]]) # by list type Tensor.(list)
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
b.tolist() # transform tensor to list

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [9]:
b # 使用方法时返回一个新值， 没有改变原本的值

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
b_size = b.size() # return torch.size() object
b_size

torch.Size([2, 3])

In [14]:
b.shape # attribute of b

torch.Size([2, 3])

In [11]:
b.numel() # return the # of elements in b

6

In [13]:
c = t.Tensor(b.size())
c

tensor([[0., 0., 0.],
        [0., 0., 0.]])

### Other common method to create tensor 

In [15]:
t.ones([2,3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
t.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
t.arange(1,6,3) # 3 is the step

tensor([1, 4])

In [19]:
t.linspace(1,10,4)

tensor([ 1.,  4.,  7., 10.])

In [21]:
t.randn(2,3, device=t.device('cuda'))

tensor([[-0.1928,  0.8163, -0.4880],
        [-0.5797,  1.5679, -0.7914]], device='cuda:0')

In [22]:
t.randperm(100)

tensor([18, 93, 12, 77, 79, 49, 70, 47, 19, 87, 54, 17, 83, 31, 42, 61, 56, 28,
        15, 97, 68, 85, 78,  3, 35, 99, 34, 20, 30,  9, 21, 13, 24, 51, 37, 33,
        95, 41, 27, 73, 59, 39, 10, 48, 91, 66, 22, 25, 63, 16, 67, 80,  5, 90,
        60, 58, 96, 55, 26, 53,  8,  4, 57, 38, 32, 44, 64, 69, 84, 76, 72, 45,
        71,  1, 40, 52, 94,  6,  2, 98, 29, 82, 65, 89, 81, 74, 88, 14, 11, 46,
        75, 86, 23, 92, 43,  0, 62,  7, 50, 36])

In [23]:
t.eye(2,3)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

### Using tensor( )

In [24]:
t.tensor(3.1415)

tensor(3.1415)

In [25]:
t.tensor([1,2])

tensor([1, 2])

In [27]:
t.Tensor([1,2])

tensor([1., 2.])

In [31]:
aa = t.tensor([])
aa.shape

torch.Size([0])

## Operation on Tensor

In [34]:
a = t.arange(0,6)
a

tensor([0, 1, 2, 3, 4, 5])

In [35]:
a.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [36]:
a.view(-1,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [39]:
b = a.view(2,3)
b.unsqueeze(1)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [42]:
b.unsqueeze(2)

tensor([[[0],
         [1],
         [2]],

        [[3],
         [4],
         [5]]])

In [43]:
b.shape

torch.Size([2, 3])

In [44]:
b[:,None].shape

torch.Size([2, 1, 3])

In [45]:
b[:,None]

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [48]:
c = b.view(1,1,1,2,3)
c.shape

torch.Size([1, 1, 1, 2, 3])

In [49]:
c.squeeze(0)

tensor([[[[0, 1, 2],
          [3, 4, 5]]]])

In [50]:
c.shape

torch.Size([1, 1, 1, 2, 3])

In [51]:
c.squeeze()

tensor([[0, 1, 2],
        [3, 4, 5]])

In [52]:
c.shape

torch.Size([1, 1, 1, 2, 3])

In [53]:
a[1] =100 # a 修改， b作为a的view，也会变，同理c作为b的view，也会改变
b

tensor([[  0, 100,   2],
        [  3,   4,   5]])

In [54]:
c

tensor([[[[[  0, 100,   2],
           [  3,   4,   5]]]]])

In [55]:
b.resize_(3,3)

tensor([[                0,               100,                 2],
        [                3,                 4,                 5],
        [28147931469906029, 28429470870339689,           7929964]])

## Index of Tensor 

In [57]:
a = t.randn(3,4)
a

tensor([[-0.6397, -0.6777, -2.2323,  0.7467],
        [ 0.4109, -1.3552,  2.1076, -0.0779],
        [ 0.5233, -0.6687,  0.1159, -1.0605]])

In [58]:
a[0,1]

tensor(-0.6777)

In [60]:
a[:,-1]

tensor([ 0.7467, -0.0779, -1.0605])

In [61]:
a[None].shape

torch.Size([1, 3, 4])

In [62]:
a[:,None,:].shape

torch.Size([3, 1, 4])

In [63]:
a > 1

tensor([[0, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)

In [64]:
a[a>1]

tensor([2.1076])

In [65]:
a[t.LongTensor([0,1])] #第0行和第1行

tensor([[-0.6397, -0.6777, -2.2323,  0.7467],
        [ 0.4109, -1.3552,  2.1076, -0.0779]])

In [66]:
a = t.arange(16)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [79]:
a = a.view(4,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [75]:
index = t.LongTensor([[0,1,2,3]])

In [76]:
index

tensor([[0, 1, 2, 3]])

In [82]:
a.gather(0,index)

tensor([[ 0,  5, 10, 15]])